# postgres:14.4
version: '3'
services:
  db:
    image: postgres:14.4
    container_name: anylistDB
    restart: always
    ports:
      - "5432:5432"
    environment:
      #POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data